name: Node.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-build
          path: |
            dist/
            package.json
            package-lock.json
          retention-days: 5
