name: Node.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_UR: "http://13.234.111.118:9000/"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=nodejs-github-actions \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_UR \
            -Dsonar.login=$SONAR_TOKEN

